### ISSUE TITLE
[bug] Emulators fail to start when defined with spaces in the actions file

### ISSUE THREAD

**Issue by HassanBahati** [invertase/firebase-emulator-action#2]
# Bug Report: Firebase Emulator Action - Emulator List Spacing Issue

## Description
The Firebase Emulator GitHub Action fails to start specified emulators when there are leading or trailing spaces in the emulator list configuration. While defining emulators `auth` and `firestore` in the actions file, adding a space before or after the emulator names prevents them from starting correctly.

## Environment
- Repository: https://github.com/HassanBahati/firebase-emulator-action
- GitHub Action: run-emulator
- Action Version: invertase/firebase-emulator-action@v1.0.0
- Firebase Tools Version: latest (installed via npm)

## Steps to Reproduce
1. In the GitHub Actions workflow file, define emulators with spaces:
```yaml
# Incorrect configuration with spaces
emulators: " auth, firestore "  # or "auth , firestore"
```

## Current Behavior
When spaces are present in the emulator list:
- The emulators fail to start
- The action does not recognize the emulator names
- No error message explicitly indicates the spacing issue

## Expected Behavior
The emulators should either:
- Start successfully despite the presence of spaces
- Or provide a clear error message indicating that spaces in the emulator list are not allowed

## Root Cause
The issue occurs because the emulator configuration is sensitive to whitespace characters. The correct format should be a comma-separated list without spaces:
```yaml
# Correct configuration
emulators: "auth,firestore"
```

## Solution
Remove all spaces from the emulator list in the workflow file:
```diff
- emulators: " auth, firestore "
+ emulators: "auth,firestore"
```

## Before Fix (With Spaces)
```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: invertase/firebase-emulator-action@v1.0.0
        with:
          emulators: " auth, firestore "  # Problematic spacing
```
![Failed Emulator Start](https://github.com/user-attachments/assets/3cfd1345-2cdb-4c3d-a200-6374511537ff)

## After Fix (Without Spaces)
```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: invertase/firebase-emulator-action@v1.0.0
        with:
          emulators: "auth,firestore"  # Correct format
```
![Successful Emulator Start](https://github.com/user-attachments/assets/24e99c10-d259-4fb6-8caa-f948cf06eacf)

## Additional Notes
- This issue affects all emulator configurations that include spaces
- The fix is straightforward but not immediately obvious to new users
- Consider adding validation or auto-trimming of whitespace in future versions
